--------------------------------------------------------
--  文件已创建 - 星期一-二月-29-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table T_MANAGER
--------------------------------------------------------

  CREATE TABLE "HR"."T_MANAGER" 
   (	"ID" NUMBER, 
	"USERNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index IDS
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."IDS" ON "HR"."T_MANAGER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table T_MANAGER
--------------------------------------------------------

  ALTER TABLE "HR"."T_MANAGER" ADD CONSTRAINT "IDS" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."T_MANAGER" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."T_MANAGER" MODIFY ("USERNAME" NOT NULL ENABLE);
 
  ALTER TABLE "HR"."T_MANAGER" MODIFY ("PASSWORD" NOT NULL ENABLE);
