--------------------------------------------------------
--  文件已创建 - 星期一-二月-29-2016   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table STUDENT2
--------------------------------------------------------

  CREATE TABLE "HR"."STUDENT2" 
   (	"STID" VARCHAR2(25 BYTE), 
	"STNAME" VARCHAR2(10 BYTE), 
	"STSEX" VARCHAR2(10 BYTE), 
	"STAGE" VARCHAR2(10 BYTE), 
	"STTEL" VARCHAR2(20 BYTE), 
	"STDEPT" VARCHAR2(20 BYTE), 
	"STADDRESS" VARCHAR2(50 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index STUDENT2_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HR"."STUDENT2_PK" ON "HR"."STUDENT2" ("STID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table STUDENT2
--------------------------------------------------------

  ALTER TABLE "HR"."STUDENT2" ADD CONSTRAINT "STUDENT2_PK" PRIMARY KEY ("STID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
 
  ALTER TABLE "HR"."STUDENT2" MODIFY ("STID" NOT NULL ENABLE);
